# -*- coding: utf-8 -*-
"""Copy of M2_Project_Hotel_Booking_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kym1MZ2LXrxz63KrRA82wUSeGg7xN5Qt

# **Project Name**    -
Hotel Booking Analysis

##### **Project Type**    - EDA
##### **Contribution**    - Individual
Adarsh Kumar

# **Project Summary -**

Hotel Booking Analysis: A Comprehensive Overview

In the world of hospitality, understanding booking patterns is essential to running a successful hotel. Hotel booking analysis involves diving deep into the data that tells us who is booking, when they’re booking, where they’re booking from, and why they might cancel. This information is crucial for hoteliers who want to optimize their services, pricing, and marketing strategies to better meet the needs of their guests and maximize their revenue.

Understanding the Guests
One of the first things to consider in hotel booking analysis is the demographic profile of guests. Who are they? Are they business travelers, families on vacation, or couples on a romantic getaway? Understanding the purpose of their travel can help hotels tailor their services. For example, business travelers might value fast Wi-Fi and meeting rooms, while vacationers might prioritize comfort and amenities like pools or spas. Knowing your guests means you can better cater to their needs and enhance their overall experience, leading to higher satisfaction and repeat bookings.

Booking Channels
Where guests book their stay is another critical aspect. The rise of online travel agencies (OTAs) like Booking.com or Expedia has changed the game, giving guests numerous options at their fingertips. However, direct bookings through a hotel’s website are often more profitable since they avoid commission fees charged by OTAs. By analyzing where bookings are coming from, hotels can decide where to focus their marketing efforts. For instance, offering special discounts for direct bookings or partnering with popular OTAs to reach a broader audience can be effective strategies.

Cancellations and Their Impact
Cancellations are an inevitable part of hotel management, but they can be a significant challenge. High cancellation rates can disrupt room availability and revenue forecasts. Understanding why guests cancel their reservations is essential. Some cancellations are due to flexible booking policies, while others might result from personal circumstances or unexpected events. By analyzing cancellation trends, hotels can adjust their policies—perhaps by offering non-refundable rates at a lower price or setting stricter cancellation terms to reduce last-minute changes. Predictive models can also be useful, allowing hotels to anticipate cancellations and manage bookings accordingly.

Seasonal Trends
Every hotel experiences fluctuations in demand throughout the year. Some periods, like summer vacations or local festivals, might see a surge in bookings, while others could be quieter. By analyzing seasonal trends, hotels can plan their pricing strategies, staffing levels, and promotional activities more effectively. For instance, during high-demand seasons, hotels can raise prices to maximize revenue, while in off-peak times, they might offer discounts or special packages to attract more guests. Understanding these patterns ensures that a hotel can maintain steady occupancy rates and optimize profits year-round.

Adapting to External Factors
External factors like economic conditions, political events, or global crises such as pandemics can dramatically impact hotel bookings. The COVID-19 pandemic, for example, led to widespread cancellations and a need for new safety protocols. Being able to adapt quickly to such changes is crucial. Hotels that monitor external trends and adjust their strategies—whether by diversifying their target markets or enhancing health and safety measures—are better positioned to weather such storms and continue attracting guests.

Conclusion
In essence, hotel booking analysis is about understanding the stories behind the numbers. By getting to know their guests, optimizing booking channels, managing cancellations, and adapting to seasonal and external changes, hotels can enhance their services, increase customer satisfaction, and ultimately boost their bottom line.

# **GitHub Link -**

# **Problem Statement**

In today’s competitive hospitality industry, the ability to effectively analyze hotel booking data has become a cornerstone for success. However, this analysis is fraught with challenges that, if not addressed, can lead to missed opportunities, revenue loss, and suboptimal guest experiences. This problem statement outlines the key issues that hotels face when attempting to understand and utilize booking data.

1. Diverse and Fragmented Data Sources
One of the primary challenges in hotel booking analysis is the fragmentation of data across multiple sources. Bookings come from various channels—online travel agencies (OTAs), direct bookings via the hotel’s website, corporate accounts, and travel agents. Each of these channels often uses different systems and formats for storing and transmitting data. Integrating this diverse data into a single, coherent system for analysis is a significant challenge. The lack of standardized data formats and the use of legacy systems further complicate this integration, making it difficult for hotels to gain a holistic view of their booking patterns.

2. High Cancellation Rates and Unpredictability
Cancellations present another major challenge in hotel booking analysis. High cancellation rates, especially from certain channels like OTAs, can lead to revenue loss and inefficient room management. Predicting cancellations is difficult due to the wide range of factors influencing guest behavior, including economic conditions, changes in travel plans, and competitive offers from other hotels. The unpredictability of cancellations makes it challenging to maintain accurate revenue forecasts and optimize occupancy rates. Hotels need to develop robust predictive models and strategies to mitigate the impact of cancellations, but the complexity of these models can be a barrier for many.

3. Seasonal and Temporal Variability
Hotel bookings are highly seasonal, with demand peaking during certain periods, such as holidays, local events, and favorable weather conditions. Conversely, there are off-peak periods where bookings drop significantly. Analyzing this variability is essential for revenue management, but it poses a challenge due to the numerous factors that influence demand. Inaccurate forecasting can lead to either overpricing during peak seasons, which may deter potential guests, or underpricing, which can result in lost revenue. During low-demand periods, hotels might struggle to attract guests without resorting to heavy discounts, which can harm the brand’s perceived value.

4. Customer Segmentation and Personalization
Understanding customer demographics and behavior is key to tailoring services and marketing efforts. However, effectively segmenting customers and personalizing their experiences based on booking data is a complex task. Hotels need to categorize guests by various criteria, such as age, nationality, purpose of stay (business or leisure), and booking preferences. The challenge lies in accurately identifying these segments and delivering personalized offers or experiences that meet their specific needs. Failure to do so can result in generic, one-size-fits-all marketing strategies that do not resonate with any particular group, leading to lower conversion rates and customer satisfaction.

5. External Factors and Unforeseen Events
External factors such as economic downturns, political instability, or global events like pandemics can have a dramatic impact on hotel bookings. These factors are often beyond the control of hotel operators but must be accounted for in booking analysis. The challenge is not only in predicting the occurrence of such events but also in quickly adapting to them. Hotels that cannot rapidly adjust their strategies in response to external shocks may suffer from prolonged periods of low occupancy and revenue decline.

Conclusion
The challenges in hotel booking analysis are multifaceted and require a comprehensive approach to overcome. Data fragmentation, high cancellation rates, seasonal variability, customer segmentation, and external factors all contribute to the complexity of this task. Addressing these issues requires investments in technology, data management, and predictive analytics, as well as a flexible approach to strategy development. By tackling these challenges head-on, hotels can unlock the full potential of their booking data, leading to more informed decision-making, enhanced guest experiences, and improved financial performance.

#### **Define Your Business Objective?**

The goal of the hotel booking analysis project is to use data to make better decisions that help the hotel grow, improve guest experiences, and increase revenue. By studying booking patterns, guest behavior, and market trends, the project aims to achieve several key objectives:

Boost Revenue and Profit: The project seeks to understand how different factors affect bookings so the hotel can adjust prices, reduce cancellations, and fill more rooms. By knowing when demand is high or low, the hotel can make smarter pricing decisions and run promotions that attract more guests.

Improve Guest Experience: By analyzing who the guests are and what they want, the hotel can offer more personalized services and tailor experiences to meet their needs. Whether it's providing special amenities for business travelers or creating family-friendly packages, the goal is to make every guest feel valued and satisfied, encouraging them to return.

Enhance Operational Efficiency: The project aims to make hotel operations smoother and more efficient. By accurately predicting demand, the hotel can ensure it has the right number of staff and the right resources available, minimizing waste and improving service delivery.

Stay Competitive in the Market: By keeping an eye on market trends, economic conditions, and what competitors are doing, the hotel can quickly adapt its strategies. This could mean targeting new customer segments, adjusting marketing efforts, or implementing new technologies to stay ahead of the competition.

Cut Costs and Manage Risks: The project also aims to find ways to reduce costs, like relying less on expensive booking channels or optimizing promotional spending. Additionally, by predicting risks such as high cancellation rates, the hotel can take steps to minimize these challenges and ensure steady revenue.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Commented out IPython magic to ensure Python compatibility.

import numpy as np
import pandas as pd
from numpy import math
from numpy import loadtxt
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
from matplotlib import rcParams

!pip install pymysql
import pymysql
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

import warnings
warnings.filterwarnings('ignore')

"""### Dataset Loading"""

# Load Datase
# CSV file loaction path
file_path='/content/drive/MyDrive/M2_project/Hotel Bookings.csv'

from google.colab import drive
drive.mount('/content/drive')

"""### Dataset First View"""

# Dataset First Look
df = pd.read_csv(file_path)
df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
df.shape

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
df.duplicated().sum()

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
df.isnull().sum()

# Visualizing the missing values
df.isnull().sum().plot(kind='bar')

"""### What did you know about your dataset?

Total Entries: 119,390,
Total Columns: 32,
Key Features:
Hotel Type: Resort or City hotel.
Booking Status: Includes cancellation data.
Lead Time: Days between booking and arrival.
Stay Duration: Split between weekend and weekday nights.
Guests: Number of adults, children, and babies.
Booking Details: Meal type, booking source, and average daily rate (ADR).
Special Requests: Total special requests made by guests.
Reservation Status: Includes final booking outcomes like Check-Out or Canceled.
Missing Data: Some missing values in children, country, agent, and company fields.
This dataset primarily tracks hotel bookings, cancellations, guest details, and stay specifics.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Variables Description

Variables Description:
hotel: Type of hotel (City or Resort).
is_canceled: Booking canceled (1) or not (0).
lead_time: Days between booking and arrival.
arrival_date: Year, month, week number, and day of arrival.
stay_duration: Nights stayed on weekends and weekdays.
guests: Number of adults, children, and babies.
meal: Type of meal plan booked.
country: Guest's country of origin.
booking_details: Market segment, distribution channel, and booking changes.
previous_bookings: History of cancellations and non-cancellations.
room_type: Reserved and assigned room types.
deposit_type: Deposit made (No, Refundable, Non-Refundable).
agent/company: Booking agent or company ID.
customer_type: Type of customer (Transient, Group).
adr: Average daily rate (price per night).
special_requests: Number of special requests made.
reservation_status: Final status of the reservation (Check-Out, Canceled, etc.).

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
df.nunique()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
#copy of original dataframe
df1 = df.copy()

# Check for missing values
print(df1.isnull().sum())

# Drop any rows with missing values
df1.dropna(inplace=True)

# Create a new column for arrival date
df1['arrival_date'] = pd.to_datetime(df1['arrival_date_year'].astype(str) + '-' + df1['arrival_date_month'].astype(str) + '-01')

# Convert categorical variables to numerical variables
df1['hotel'] = df['hotel'].map({'City Hotel': 0, 'Resort Hotel': 1})
df1['meal'] = df['meal'].map({'BB': 0, 'FB': 1, 'HB': 2, 'SC': 3})
df1['market_segment'] = df['market_segment'].map({'Corporate': 0, 'Direct': 1, 'Groups': 2, 'Offline TA/TO': 3, 'Online TA': 4, 'Undefined': 5})
df1['distribution_channel'] = df['distribution_channel'].map({'Corporate': 0, 'Direct': 1, 'GDS': 2, 'TA/TO': 3, 'Undefined': 4})
df1['customer_type'] = df['customer_type'].map({'Contract': 0, 'Group': 1, 'Transient': 2, 'Transient-Party': 3})
df1['reservation_status'] = df['reservation_status'].map({'Canceled': 0, 'Check-Out': 1, 'No-Show': 2})

# Create a new column for total nights stayed
df1['total_nights_stayed'] = df['stays_in_week_nights'] + df1['stays_in_weekend_nights']

# Create a new column for average daily rate (ADR)
df1['adr'] = df1['adr']

# Create a new column for total revenue
df1['total_revenue'] = df1['adr'] * df1['total_nights_stayed']

# Check for outliers in the data
print(df1.describe())

# Remove any outliers in the data
Q1 = df1['total_revenue'].quantile(0.25)
Q3 = df1['total_revenue'].quantile(0.75)
IQR = Q3 - Q1
df1 = df1[~((df1['total_revenue'] < (Q1 - 1.5 * IQR)) | (df1['total_revenue'] > (Q3 + 1.5 * IQR)))]

# Save the cleaned dataset to a new CSV file
df1.to_csv('cleaned_hotel_bookings.csv', index=False)

"""### What all manipulations have you done and insights you found?

Booking Cancellations: The dataset tracks whether bookings were canceled or completed, which can be useful for analyzing cancellation trends.
Lead Time: The lead_time column provides information on how far in advance bookings are made, which could help in forecasting demand.
Stay Patterns: The dataset includes information on stays_in_weekend_nights and stays_in_week_nights, allowing analysis of guest stay patterns across weekdays and weekends.
Guest Composition: Data on the number of adults, children, and babies gives insights into family and solo traveler trends.
Special Requests: The total_of_special_requests field shows how many additional services were requested, which can be linked to guest satisfaction or types of stays.
Reservation Status: Final reservation status (e.g., Check-Out, Canceled) helps in understanding customer behavior and the likelihood of cancellations.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code

# set the plot size
plt.figure(figsize=(10,6))

#scattter plot using seaborn
sns.scatterplot(x='lead_time', y = 'adr',hue = 'is_canceled',data= df1, palette='coolwarm')

#Add plot title and labels
plt.title('Lead Time vs. ADR',fontsize =15)
plt.xlabel('Lead Time(Days)',fontsize =12)
plt.ylabel('Average Daily Rate(ADR)',fontsize =12)

#Display the plot
plt.show()

"""##### 1. Why did you pick the specific chart?

I chose the scatter plot for this specific visualization because it is ideal for understanding the relationship between two continuous variables: lead time and average daily rate (ADR). Here's why:

1. Relationship Between Two Numerical Variables:
Lead Time and ADR are both numerical variables.

A scatter plot clearly shows how these two variables interact, allowing us to detect patterns, trends, or correlations.

2. Distinguishing Cancellations:
By adding a hue to the scatter plot based on the is_canceled variable, we can distinguish between canceled and non-canceled bookings, which adds a third dimension to the analysis.
This allows us to explore whether certain lead times or ADRs are associated with a higher likelihood of cancellations.

3. Trend Identification:
The scatter plot is effective for spotting clusters, outliers, or trends. For example, we might observe that bookings with very long lead times are more prone to cancellations or that lower ADRs result in fewer cancalations

4. Simple and Informative:
Scatter plots are simple yet powerful in showing relationships in large datasets without overcomplicating the visualization.
It helps in quickly identifying whether there's a correlation between the two variables (e.g., if higher ADRs lead to fewer cancellations or how lead time affects pricing).

##### 2. What is/are the insight(s) found from the chart?

The scatter plot highlights that both lead time and ADR influence the likelihood of cancellations. Long lead times and lower ADR bookings are more prone to cancellations, while last-minute bookings with higher ADRs are more likely to be completed.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

yes,the gained insights wikk hekp creating a possitive business impact.
Here are some positive Business Impact insights:
1.Identifying Pricing Trends
2.Cancellation Patterns
3.Optomizing Lead Time

Yes there are some negative insights that lead to negative growth likes:
1.High Cancellation Rates with High ADR
2.Short Lead Times and Lower ADRs

Specific Justifications:
Cancellation Trends: If cancellations are predominantly clustered around certain ADR values or lead times, this can highlight areas where your pricing strategy or booking policies may be causing issues. For instance, high ADRs with high cancellation rates could mean that customers find the price too steep and are more likely to cancel if they feel they can get a better deal closer to their stay.

Revenue Management: Insights from the scatter plot can guide you on how to better manage revenue. For example, if longer lead times are associated with higher ADRs and lower cancellations, then promoting early bookings could enhance profitability.

#### Chart - 2
"""

# Chart - 2 visualization code

# Calculate cancellation rate for each hotel type
# Calculate booking cancellations by hotel type
booking_cancellations = df1[df1['is_canceled'] == 1]
booking_cancellations_by_hotel_type = booking_cancellations['hotel'].value_counts()

# Create a bar chart
plt.figure(figsize=(10, 6))
booking_cancellations_by_hotel_type.plot(kind='bar')
plt.title('Booking Cancellations by Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('Number of Cancellations')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a bar chart to compare the cancellation rates between City Hotel and Resort Hotel

##### 2. What is/are the insight(s) found from the chart?

The insight is taht City Hotel has a higher cancellation rate compared to Resort Hotel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive bsiness impact by identifying areas for improvement in City Hotel's booking process or customer service to reduce cancellations.

#### Chart - 3
"""

# Chart - 3 visualization code

# Lead Time Distribution

# Create histogram
plt.hist(df['lead_time'], bins=50)
plt.xlabel('Lead Time (days)')
plt.ylabel('Frequency')
plt.title('Lead Time Distribution')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a histogram to visualize the distribution of lead times .

##### 2. What is/are the insight(s) found from the chart?

The insight is that lead time distribution is skewed, with most bookings made within a short period.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by optimizing pricing and inventory management strategies based on lead time patterns.

#### Chart - 4
"""

# Chart - 4 visualization code
# ADR vs. Market Segment

# Create scatter plot
plt.scatter(df['market_segment'], df['adr'])
plt.xlabel('Market Segment')
plt.ylabel('Average Daily Rate (ADR)')
plt.title('ADR vs. Market Segment')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a scatter plot to explore the relationship between ADR and market segment.

##### 2. What is/are the insight(s) found from the chart?

The insight is that there is a positive coorelation between ADR and market segment, with higher ADRs im certain segments

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by targeting high-value market segments and optimizing strategies.

#### Chart - 5
"""

# Chart - 5 visualization code
# Total Nights Stayed Distribution

# Create histogram
plt.hist(df['stays_in_week_nights'] + df['stays_in_weekend_nights'], bins=50)
plt.xlabel('Total Nights Stayed')
plt.ylabel('Frequency')
plt.title('Total Nights Stayed Distribution')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a histogram to visualize the distribution of total nights stayed.

##### 2. What is/are the insight(s) found from the chart?

The insight is taht the distribution is skewed, with most bookings staying for a short period

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by optimizing room allocatio and pricing strategies based on stay duration patterns.

#### Chart - 6
"""

# Chart - 6 visualization code
# Special requests by hotel type

# Calculate special request rate for each hotel type (assuming special requests are related to children or babies)
city_hotel_special_requests = df[df['hotel'] == 'City Hotel']['children'].mean()
resort_hotel_special_requests = df[df['hotel'] == 'Resort Hotel']['children'].mean()

# Create bar chart
plt.bar(['City Hotel', 'Resort Hotel'], [city_hotel_special_requests, resort_hotel_special_requests])
plt.xlabel('Hotel Type')
plt.ylabel('Average Number of Children per Booking')
plt.title('Special Requests by Hotel Type')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a bar chart to compare the special request rates between City Hotel and Resort Hotel.

##### 2. What is/are the insight(s) found from the chart?

The Insight is that Resort Hotel has a higher special request rate compared to city Hotel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insigth can help create a positive business impact by identifying areas for improvement in city Hotel's special request handling process.

#### Chart - 7
"""

# Chart - 7 visualization code

#Booking Status by Arrival Month

# Create bar chart
df1.groupby('arrival_date_month')['reservation_status'].value_counts().unstack().plot(kind='bar')
plt.xlabel('Arrrival Month')
plt.ylabel('count')
plt.title('Reservation status by Arrival Month')
plt.legend(title='Reservation Status')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a bar chart to visualize the booking status by arrival month.

##### 2. What is/are the insight(s) found from the chart?

The insight is that there are seasonal patterns in booking status, with more cancellations during certain months.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

The insight can help create a positive business impact by optimizing pricing and inventory management strategies based on seasonal patterns.

#### Chart - 8
"""

# Chart - 8 visualization code
# Reservation Status by Customer Type

# Calculate reservation status for each customer type
#Create Bar chart
df1.groupby('customer_type')['reservation_status'].value_counts().unstack().plot(kind='bar')
plt.xlabel('Customer Type')
plt.ylabel('Count')
plt.title('Reservation Status by Customer Type')
plt.legend(title = 'Reservation Status')
plt.show()

"""##### 1. Why did you pick the specific chart?

I pocked a bar chart to visualize the reservation status by customer type.

##### 2. What is/are the insight(s) found from the chart?

The is that there are three differences in reservation status between customer types, with certain types having higher cancellations rates .

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by identifying areas for improvements in customer service and targetting high_value customer segments.

#### Chart - 9
"""

# Chart - 9 visualization code
# Adults and Children by Market Segment

# Calculate adults and children for each market segment
market_segment_adults = df.groupby('market_segment')['adults'].mean()
market_segment_children = df.groupby('market_segment')['children'].mean()

# Create bar chart
plt.bar(market_segment_adults.index, market_segment_adults.values, label='Adults')
plt.bar(market_segment_children.index, market_segment_children.values, label='Children')
plt.xlabel('Market Segment')
plt.ylabel('Number of Adults/Children')
plt.title('Adults and Children by Market Segment')
plt.legend()
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a bar chart to compare the number of adults and children by market segment.

##### 2. What is/are the insight(s) found from the chart?

The insight is that certain market segments have a higher proportion of adults or children.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by targetting market segment with specific amenities and services.

#### Chart - 10
"""

# Chart - 10 visualization code
# Car parking Spaces Required by Hotel
# Calculate car parking spaces required by hotel
car_parking_spaces_required = df.groupby('hotel')['required_car_parking_spaces'].sum()

# Create a bar chart
plt.figure(figsize=(10, 6))
car_parking_spaces_required.plot(kind='bar')
plt.title('Car Parking Spaces Required by Hotel')
plt.xlabel('Hotel')
plt.ylabel('Number of Car Parking Spaces Required')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a bar cart to compare the car parking spaces required by hotel type.

##### 2. What is/are the insight(s) found from the chart?

The insight is that City Hotel requires more car parking space compared to Resort Hotel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help a positive business impact by optimizing car parking sapce allocation and pricing strategies.

#### Chart - 11
"""

# Chart - 11 visualization code
#Bookings by Meal Type


import matplotlib.pyplot as plt

# Calculate bookings for each meal type
meal_type_bookings = df['meal'].value_counts()

# Create bar chart
plt.bar(meal_type_bookings.index, meal_type_bookings.values)
plt.xlabel('Meal Type')
plt.ylabel('Bookings')
plt.title('Bookings by Meal Type')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a bar chart to visualize the bookings by meal type.

##### 2. What is/are the insight(s) found from the chart?

The insight is that certain meal types are more popular than others.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by optimizing meal offerings and pricing strategies.

#### Chart - 12
"""

# Chart - 12 visualization code
#Reservation Status by Year

# Calculate reservation status for each year
# Create line chart
pivot_table = df1.pivot_table(index='arrival_date_year',columns = 'reservation_status',aggfunc = 'size', fill_value =0 )

sns.lineplot(data = pivot_table)
plt.xlabel('Year')
plt.ylabel('Count')
plt.title('Reservation Status by Year')
plt.legend(title='Reservation Status')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a line chart to visualize the reservation status b year.

##### 2. What is/are the insight(s) found from the chart?

The insight is that there are trends and patterns in reservation status over time.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by identifying areas for improvement in customer service and optimizing pricing strategies based on historical trends.

#### Chart - 13
"""

# Chart - 13 visualization code
# Adults vs. Children per Booking
import matplotlib.pyplot as plt

# Create scatter plot
plt.scatter(df['adults'], df['children'])
plt.xlabel('Number of Adults')
plt.ylabel('Number of Children')
plt.title('Adults vs. Children per Booking')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a scatter plot to explore the relationship between adults and children per booking.

##### 2. What is/are the insight(s) found from the chart?

The insight is that there is a positive corelation between adults and children per booking, with more adults associated with more chilren.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight can help create a positive business impact by optimizing room allocation and pricing strategies based on family booking patterns.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

#select the columns to include in the correlation heatmap

# Select the columns to include in the correlation heatmap
columns = ['lead_time', 'stays_in_week_nights', 'stays_in_weekend_nights', 'adr', 'total_nights_stayed', 'total_revenue']

# Create a correlation matrix
corr_matrix = df1[columns].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='RdYlGn', square=True,
            linewidths=0.5, linecolor='black', fmt='.2f',
            cbar_kws={'shrink': 0.7})
plt.title('Correlation Heatmap')
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a correlation heatmap because it is a powerful tool for visualizing the relationships between multiple variables. The heatmap allows us to see the strength and direction of the correlations between each pair of variables , which can help us identify patters and relationships in the data.

##### 2. What is/are the insight(s) found from the chart?

From the correlation heatmap, we can see that:
.There is a strong positive correlation between 'total_nights_stayed' and 'total_revenue

*   There is a strong positive correlation between 'total_nights_stayed' and 'total_revenue', which makes sense because the longer a guest stays,the more revenue the hotel generates.

*   There is a moderate positive correlation between 'adr' and 'total_evenue', which suggests that higher average daily rates and associated with higher total revenue.

* There is a weak negative correlation beween 'lead_time' and 'total_revenue', which may suggest that guests who book their stays further in advanced tend to generate less revenue for the hotel.

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
# Calculate total nights stayed
df1['total_nights_stayed'] = df1['stays_in_week_nights'] + df['stays_in_weekend_nights']

# Calculate total revenue
df1['total_revenue'] = df1['adr'] * df1['total_nights_stayed']

# Select the columns to include in the pair plot
columns = ['lead_time', 'stays_in_week_nights', 'stays_in_weekend_nights', 'adr', 'total_nights_stayed', 'total_revenue']

# Create a pair plot
sns.pairplot(df1[columns], diag_kind='kde', markers=['o', 's', 'D', '^', 'v', '*'])
plt.show()

"""##### 1. Why did you pick the specific chart?

I picked a pair plot becase it is a powerfool tool for visualizing the relationships betweeen multiple variables . The pair plot allows us to see the the distribution of each variable, as well as the relationships between each pair of variables. This can help us identify patterns and correlation in the data that might not be immediately apparent from a singleplot.

##### 2. What is/are the insight(s) found from the chart?

From the pair plot,we can see several insights:


*   There is a strong positive correlation betweeen total nights stayed and total revenue, which makes sese because the longer a guest stays , the more the revenue the hotel genereates.
*   There is a moderate positive corrletion between ADR  and total revenue , which suggests that higher average daily rates are associated with higher total revenue.


*  There is a moderate positive correlation between ADR and total revenue, which suggests taht higher average daily rates are associated with higher total revenue.

*   There is a weak negative correlation betwween lead time and total revenue, which suggests that higher average daily rates are associated with higher total revenue.

Chart-16
"""

#Bar chart of Average Daily Rate(ADR) by Hotel Type
adr_by_hotel_type = df1.groupby('hotel')['adr'].mean()

#Create a bar chart
plt.figure(figsize=(10,6))
adr_by_hotel_type.plot(kind='bar')
plt.title('Average Daily Rate(ADR) by Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('ADR')
plt.show()

"""1. Why did you pick the specific chart?

I picked a bar chart because it is a simple and effective way to compare the average daily rate(ADR) across differenthotel types.

2. What is/are the insight(s) found from the chart?

The chart shows that the ADR for Resort Hotels is significantly higher than for City Hotels. This suggests that Resort Hotels are able to charge higher rates due to their unique amenties and services.

3. Are there any insights that lead to negative growth? Justify with specific reason.

No,there are no insights gained from this chart that lead to growth .

# **Conclusion**

In this analysis, we explored the hotel booking dataset to identify trends, patterns and correlations that can inform business decisions. We created various visualizations,incluing a corelation heatmap and pair plot , to gain insights into the relationships between different variables.

Our analysis revealed several key findings, including:


*   A strong positive correlation between total nights stayed and total revnue.

*   A moderate positive correlation between ADR and total revenue.

*   Skewed distribution of lead time , ADR andd total nights stayed

Based on these findings, we suggested several strategies to achieve the business objective of increasing revenue and improveing hotel performance, including optimizingpricing strategy ,targeting long-staysguests, improving lead time management , enhancing guest experience, and monitoring and adjusting strategies as needed.

By implementing these straties, the hotel can increase revenue, improve performance, and achieve its business objecives. Our analysis demonstrates the importance of data-driven decision-making in the hospitality industry and highlights the potential for data analysis to drive business success.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""